user1 = User.create(username: "Henno", email: "henno@gmail.com", password: "12345")

bangkok = City.create(name: "Bangkok", country: "Thailand")
capetown = City.create(name: "Cape Town", country: "South Africa")
newyork = City.create(name: "New York City", country: "United States of America")
paris = City.create(name: "Paris", country: "France")
austin = City.create(name: "Austin", country: "United States of America")
chiangmai = City.create(name: "Chiang Mai", country: "Thailand")
medellin = City.create(name: "Medellin", country: "Colombia")
budapest = City.create(name: "Budapest", country: "Hungary")

tip1 = Tip.create(content: "Daniel Thaiger has the best burgers in Bangkok.", category: "Food", user_id: user1.id , city_id: bangkok.id ,votes: 1)
tip1 = Tip.create(content: "Most expat/nomad types can be found in the Nimmanhaemin area.", category: "Accommodation", user_id: user1.id, city_id: chiangmai.id ,votes: 1)
tip1 = Tip.create(content: "The BTS(skytrain) and MRT(subway) are usually the quickest ways to get around town.", category: "Transport", user_id: user1.id, city_id: bangkok.id ,votes: 1)
tip1 = Tip.create(content: "Free Tuk Tuks are usually a scam where they take you on a detour to a store where you get pressured into making a purchase", category: "Scams/Security", user_id: user1.id, city_id: chiangmai.id ,votes: 1)
tip1 = Tip.create(content: "Dtac or AIS are the best mobile carriers in Thailand.", category: "Internet", user_id: user1.id, city_id: chiangmai.id ,votes: 1)
tip1 = Tip.create(content: "There's an abondoned skyscraper called the Ghost Tower that has one of the best views in the city. You just need to climb up 50 flights of stairs.", category: "Things to do", user_id: user1.id, city_id: bangkok.id ,votes: 1)
tip1 = Tip.create(content: "Border runs to Mai Sai can buy you an extra 2 weeks of travel time in Thailand", category: "Visa", user_id: user1.id, city_id: chiangmai.id ,votes: 1)
